import ForgeForm from "@/components/ForgeForm";
import { supabase } from "@/lib/supabase";
import { Area } from "@/lib/types";
import Link from "next/link";
import { Suspense } from "react";

export const revalidate = 300;

export default async function LandingPage() {
  const [areasResult, planCountResult, recentPlansResult] = await Promise.all([
    supabase.from("areas").select("*").order("name"),
    supabase.from("plan_requests").select("*", { count: "exact", head: true }),
    supabase.from("shared_plans").select(`
      total_cost,
      spots (
        name,
        areas (
          name
        )
      )
    `).order("created_at", { ascending: false }).limit(4)
  ]);

  const areas = areasResult.data || [];
  const planCount = planCountResult.count || 0;
  const recentPlans = (recentPlansResult.data || []).filter(p => p.spots && (p.spots as any).areas);

  return (
    <main className="min-h-screen bg-brand-green text-white antialiased">
      {/* Hero Section */}
      <div className="relative pt-20 pb-32 px-4 overflow-visible">
        <div className="max-w-4xl mx-auto text-center space-y-8">
          <h1 className="type-display text-white">
            Stop the group chat wahala. <br />
            <span className="text-brand-yellow">Get one complete plan in 3s.</span>
          </h1>
          <p className="type-body text-white/80 max-w-2xl mx-auto">
            Input 4 simple fields. Get the exact food cost, transport estimate, and "why it fits" note. Copy to WhatsApp and go.
          </p>

          {/* Form Card Container */}
          <div className="mt-12 px-4 w-full relative z-10">
            <div className="bg-white rounded-[20px] shadow-[0px_24px_48px_rgba(0,0,0,0.15)] overflow-hidden">
              <Suspense fallback={<div className="h-96 shimmer-bg opacity-10 rounded-[20px]" />}>
                <ForgeForm areas={areas} />
              </Suspense>
            </div>
          </div>
        </div>
      </div>

      {/* Social Proof Section */}
      <div className="bg-white text-text-primary py-24 px-4">
        <div className="max-w-4xl mx-auto text-center space-y-12">
          {recentPlans.length > 0 && (
            <div className="space-y-6">
              <h2 className="type-label text-text-muted">Recently planned outings</h2>
              <div className="flex flex-wrap justify-center gap-3">
                {recentPlans.map((plan: any, i) => (
                  <div key={i} className="bg-surface-grey border border-border-default rounded-lg px-4 py-3 flex items-center gap-2">
                    <span className="type-label text-text-primary lowercase first-letter:uppercase">{plan.spots.name}</span>
                    <span className="text-border-default">&bull;</span>
                    <span className="type-label text-brand-green">₦{plan.total_cost.toLocaleString()}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="space-y-4">
            <p className="type-heading text-text-primary">
              {planCount > 0 ? (
                <>
                  Join <span className="text-brand-green">{planCount.toLocaleString('en-NG')}</span> Lagos squads who have already planned their outing.
                </>
              ) : (
                "Be the first Lagos squad to plan your outing today."
              )}
            </p>
            {recentPlans.length > 0 && (
              <p className="type-caption text-text-muted">
                Generated by {planCount.toLocaleString()} Lagos squads.
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="py-12 text-center text-white/60 space-y-3">
        <p className="type-body text-white/50">&copy; 2026 OyaPlan.com &middot; Built in Lagos.</p>
        <Link href="/list-your-spot" className="type-label text-white/40 hover:text-white transition-colors">
          Own a Lagos spot? Get listed &rarr;
        </Link>
      </footer>
    </main>
  );
}
