import ForgeForm from "@/components/ForgeForm";
import { supabase } from "@/lib/supabase";
import { Area } from "@/lib/types";
import Link from "next/link";
import { Suspense } from "react";

export const revalidate = 300;

export default async function LandingPage() {
  const [areasResult, planCountResult, recentPlansResult] = await Promise.all([
    supabase.from("areas").select("*").order("name"),
    supabase.from("plan_requests").select("*", { count: "exact", head: true }),
    supabase.from("shared_plans").select(`
      total_cost,
      spots (
        name,
        areas (
          name
        )
      )
    `).order("created_at", { ascending: false }).limit(4)
  ]);

  const areas = areasResult.data || [];
  const planCount = planCountResult.count || 0;
  const recentPlans = (recentPlansResult.data || []).filter(p => p.spots && (p.spots as any).areas);

  return (
    <main className="min-h-screen bg-[#008751] text-white">
      {/* Hero Section */}
      <div className="relative overflow-hidden pt-16 pb-32 px-4">
        <div className="max-w-4xl mx-auto text-center space-y-8">
          <h1 className="text-5xl md:text-6xl font-black leading-tight tracking-tighter">
            Stop the group chat wahala. <br />
            <span className="text-[#FCD116]">Get one complete plan in 3s.</span>
          </h1>
          <p className="text-lg md:text-xl text-white/90 max-w-2xl mx-auto font-medium">
            Input 4 simple fields. Get the exact food cost, transport estimate, and "why it fits" note. Copy to WhatsApp and go.
          </p>

          {/* Form */}
          <div className="mt-12 px-4 w-full space-y-4">
            <Suspense fallback={<div className="h-96 animate-pulse bg-white/10 rounded-2xl" />}>
              <ForgeForm areas={areas} />
            </Suspense>
          </div>
        </div>
      </div>

      {/* Social Proof */}
      <div className="bg-white text-gray-900 py-16 px-4">
        <div className="max-w-4xl mx-auto text-center space-y-10">
          {recentPlans.length > 0 && (
            <div className="space-y-6">
              <p className="text-[11px] font-black uppercase tracking-widest text-gray-400">
                Recently planned outings
              </p>
              <div className="flex flex-wrap justify-center gap-3">
                {recentPlans.map((plan: any, i) => (
                  <div key={i} className="bg-white border border-gray-100 rounded-lg px-4 py-2.5 shadow-sm text-sm font-medium flex items-center gap-2">
                    <span className="text-gray-900">{plan.spots.name}</span>
                    <span className="text-gray-300">&bull;</span>
                    <span className="text-[#008751] font-bold">₦{plan.total_cost.toLocaleString()}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="space-y-2">
            <p className="text-xl md:text-2xl font-bold tracking-tight text-gray-900">
              {planCount > 0 ? (
                <>
                  Join <span className="text-[#008751] font-black">{planCount.toLocaleString('en-NG')}</span> Lagos squads who have already planned their outing.
                </>
              ) : (
                "Be the first Lagos squad to plan your outing today."
              )}
            </p>
            {recentPlans.length > 0 && (
              <p className="text-xs text-gray-400 font-medium">
                Generated by {planCount.toLocaleString()} Lagos squads.
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="py-8 text-center text-white/60 text-[15px] space-y-2">
        <p>&copy; 2026 OyaPlan.com &middot; Built in Lagos.</p>
        <Link href="/list-your-spot" className="text-white/40 hover:text-white transition-colors text-xs font-medium">
          Own a Lagos spot? Get listed &rarr;
        </Link>
      </footer>
    </main>
  );
}
