"use client";

import { Button } from "@/components/ui/button";
import { MessageSquare } from "lucide-react";
import { Plan } from "@/lib/types";

interface WhatsAppCopyButtonProps {
  plan: Plan;
}

export default function WhatsAppCopyButton({ plan }: WhatsAppCopyButtonProps) {
  const handleCopy = () => {
    const text = `*OyaPlan: The Squad Outing Plan* 🇳🇬

📍 *Spot:* ${plan.spot.name}
🗺️ *Address:* ${plan.spot.address}

💰 *Estimated Costs:*
- Food/Drinks: ₦${plan.foodCost.toLocaleString()}
- Transport: ₦${plan.transportCost.toLocaleString()}
- *Total Landed Cost: ₦${plan.totalCost.toLocaleString()}*

💡 *Why it fits:*
${plan.whyItFits}

Generated by OyaPlan.com`;

    const encodedText = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encodedText}`, "_blank");
  };

  return (
    <Button 
      onClick={handleCopy}
      className="w-full bg-[#25D366] hover:bg-[#128C7E] text-white font-bold flex items-center justify-center gap-2 h-12"
    >
      <MessageSquare className="w-5 h-5" />
      Copy to WhatsApp
    </Button>
  );
}
