"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { MessageSquare, Link as LinkIcon, Loader2, Check } from "lucide-react";
import { Plan, ForgeInput } from "@/lib/types";
import { createShareablePlan } from "@/lib/actions/sharePlan";

interface WhatsAppCopyButtonProps {
  plan: Plan;
  input: ForgeInput;
  variant?: 'filled' | 'outlined';
}

export default function WhatsAppCopyButton({ plan, input, variant = 'filled' }: WhatsAppCopyButtonProps) {
  const [copied, setCopied] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [sharing, setSharing] = useState(false);
  const [shareError, setShareError] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);
  const [isPressed, setIsPressed] = useState(false);

  const ensureShareUrl = async () => {
    if (shareUrl) return shareUrl;
    setSharing(true);
    try {
      const uuid = await createShareablePlan(plan, input);
      if (uuid) {
        const url = `https://oyaplan.com/plan/${uuid}`;
        setShareUrl(url);
        return url;
      }
      setShareError(true);
      setTimeout(() => setShareError(false), 2000);
      return null;
    } catch (e) {
      setShareError(true);
      setTimeout(() => setShareError(false), 2000);
      return null;
    } finally {
      setSharing(false);
    }
  };

  const isMobile = typeof navigator !== 'undefined' && /Android|iPhone/i.test(navigator.userAgent);

  const handleAction = async () => {
    // Physical press effect
    setIsPressed(true);
    setTimeout(() => setIsPressed(false), 80);

    const url = await ensureShareUrl();
    const text = `*OyaPlan: The Squad Outing Plan* 🇳🇬

📍 *Spot:* ${plan.spot.name}
🗺️ *Address:* ${plan.spot.address}

💰 *Estimated Costs:*
- ${plan.spot.has_food !== false ? "Food/Drinks" : "Entry/Activity"}: ₦${plan.foodCost.toLocaleString()}
- Transport: ₦${plan.transportCost.toLocaleString()}
- *Total Landed Cost: ₦${plan.totalCost.toLocaleString()}*

💡 *Why it fits:*
${plan.whyItFits}

Generated by OyaPlan.com
View full plan: ${url || "https://oyaplan.com"}`;

    if (isMobile) {
      window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
    } else {
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleShareLink = async () => {
    const url = await ensureShareUrl();
    if (url) {
      navigator.clipboard.writeText(url);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
    }
  };


  return (
    <div className="flex flex-col gap-2 w-full">
      <Button 
        onClick={handleAction}
        disabled={sharing}
        style={{ 
          transform: isPressed ? 'scale(0.96)' : 'scale(1)',
          transition: isPressed ? 'transform 80ms ease-out' : 'transform 120ms cubic-bezier(0.34, 1.56, 0.64, 1)'
        }}
        className={`w-full type-subheading flex items-center justify-center gap-2 h-[52px] rounded-[10px] tap-feedback border-2 whatsapp-confirm ${
          copied 
            ? "bg-brand-green border-brand-green text-white" 
            : variant === 'filled'
              ? "bg-[#25D366] border-[#25D366] text-white hover:bg-[#128C7E] hover:border-[#128C7E]"
              : "bg-white border-[#25D366] text-[#25D366] hover:bg-[#25D366]/5"
        }`}
      >
        {sharing ? (
          <Loader2 className="w-[18px] h-[18px] animate-spin" />
        ) : copied ? (
          <Check className="w-[18px] h-[18px]" />
        ) : (
          <MessageSquare className="w-[18px] h-[18px]" />
        )}
        {copied ? (
          "Copied! Paste in chat ✓"
        ) : isMobile ? (
          "Send via WhatsApp"
        ) : (
          "Copy for WhatsApp"
        )}
      </Button>
      
      <Button
        onClick={handleShareLink}
        disabled={sharing}
        className="w-full bg-surface-grey hover:bg-gray-200 text-text-secondary type-body flex items-center justify-center gap-2 h-[44px] transition-all rounded-[10px] border-none tap-feedback"
      >
        {sharing ? (
          <Loader2 className="w-4 h-4 animate-spin text-brand-green" />
        ) : (
          <LinkIcon className="w-4 h-4 text-text-muted" />
        )}
        {linkCopied ? (
          "Link copied!"
        ) : shareError ? (
          "Try again"
        ) : (
          "Share Link"
        )}
      </Button>
    </div>
  );
}
